#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷 Styling, Linting and testing the project project before committing'

npx lint-staged

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'


